server:
  port: 8083

spring:
  application:
    name: Configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhonatanbacilio/Configuration-WorldSneakers.git
          default-label: main
          skip-ssl-validation: true
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
