server:
  port: 8082

spring:
  application:
    name: Proj-Gateway-Client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: servicio1
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: servicio2
          uri: http://localhost:9001
          predicates:
            - Path=/api/productos/**
          filters:
            - AuthenticationFilter

        - id: servicio3
          uri: http://localhost:9002
          predicates:
            - Path=/api/clientes/**
          filters:
            - AuthenticationFilter
