spring:
  application:
    name: REST-Cliente
  config:
   import:
      optional:configserver:http://localhost:8083

eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka/
